# 4614: 2.26m -> measured 2.90 m
# 3500: 2.64m -> measured 4.57 m
# 4100: 2.44m -> measured 3.64 m
# 5500: 2.74m -> measured 3.01 m
# 6500: 2.60m -> measured 2.408 m
# 6100: 2.5654 m -> measured 2.541 m
# 6050: 2.8702 m -> measured 2.866 m

# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 6050
speed_to_erpm_offset: 0.0

# Set gains for converting acceleration to current and brake control values
accel_to_current_gain: 100
accel_to_brake_gain: -80

tachometer_ticks_to_meters_gain: -0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 20.0 # radians/second
servo_smoother_rate: 100.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 5.0 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -0.88
# -1.2135 -> 60.0 inches, goal: 67.79 inches.
# -1.25   -> 59.5 inches, goal: 67.79 inches.
# -1.10   -> 63.0 inches, goal: 67.79 inches.
# -1.00   -> 61.5 inches, goal: 67.79 inches.
# -0.80   -> 75.0 inches, goal: 67.79 inches.
# -0.95   -> 64.0 inches, goal: 67.79 inches.
# -0.90   -> 66.5 inches, goal: 67.79 inches.
# -0.88   -> 67.5 inches, goal: 67.79 inches.

steering_angle_to_servo_offset: 0.48
# 0.5: right

vesc_to_odom/odom_frame: odom_rpm
# publish odom to base link tf
#vesc_to_odom/publish_tf: true
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
wheelbase: .32

vesc_driver:
  port: /dev/sensors/vesc
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 100.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -23250
  speed_max: 23250
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.15
  servo_max: 0.85
